/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "flow_definition.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(InterfaceMessage, InterfaceMessage, AUTO)


PB_BIND(SimulatorMessage, SimulatorMessage, AUTO)


PB_BIND(FlowInfo, FlowInfo, AUTO)


PB_BIND(ConstantFlow, ConstantFlow, AUTO)


PB_BIND(ManualFlow, ManualFlow, AUTO)


PB_BIND(DynamicFlow, DynamicFlow, AUTO)


PB_BIND(DynamicFlowInterval, DynamicFlowInterval, AUTO)


PB_BIND(InformationRequest, InformationRequest, AUTO)


PB_BIND(VersionInfo, VersionInfo, AUTO)







